{"name": "Авторизация существующего пользователя с неверным паролем", "status": "passed", "description": "Тест проверяет появление ошибки,при попытке авторизоваться с неверным паролем", "start": 1724065597124, "stop": 1724065597369, "uuid": "7660004d-d1b9-4292-a36e-564e43914854", "historyId": "0c088f105c0c5bc5fddf48b28f2f74ff", "testCaseId": "0c088f105c0c5bc5fddf48b28f2f74ff", "fullName": "tests.test_login_user.TestLoginUser#test_login_user_incorrect_password", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "DESKTOP-L3DLL49"}, {"name": "thread", "value": "13308-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}