{"name": "Авторизация существующего пользователя с неверным email", "status": "passed", "description": "Тест проверяет появление ошибки,при попытке авторизоваться с неверным email", "start": 1723885834266, "stop": 1723885834549, "uuid": "1847a25e-a351-4e85-8367-1c5baa9711f0", "historyId": "0e9b7e9698dbc63b945ffce965e0c30b", "testCaseId": "0e9b7e9698dbc63b945ffce965e0c30b", "fullName": "tests.test_login_user.TestLoginUser#test_login_user_incorrect_email", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "DESKTOP-L3DLL49"}, {"name": "thread", "value": "14372-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}