{"name": "Ошибка при попытке создать заказ неавторизованным пользователем с неверным хешем ингредиентов", "status": "failed", "statusDetails": {"message": "AssertionError: assert 400 == 500\n +  where 400 = <Response [400]>.status_code", "trace": "self = <test_create_order.TestCreateOrder object at 0x00000200E7CD0460>\n\n    @allure.title(\"Ошибка при попытке создать заказ неавторизованным пользователем с неверным хешем ингредиентов\")\n    @allure.description(\"Тест проверяет, что при заказе с неверным хешом\"\n                        \"ингредиентов, появляется ошибка\")\n    def test_create_order_not_authorized_user_incorrect_ingredients(self):\n        response = requests.post(OrderURL.order_url, data=IngredientsBurger.incorrect_burger)\n>       assert response.status_code == 500\nE       assert 400 == 500\nE        +  where 400 = <Response [400]>.status_code\n\ntests\\test_create_order.py:39: AssertionError"}, "description": "Тест проверяет, что при заказе с неверным хешомингредиентов, появляется ошибка", "start": 1723885828137, "stop": 1723885828464, "uuid": "7023679c-3207-448d-ab0f-b7f9e7e1cff4", "historyId": "769064dabf2c6a42936c50307d6308b7", "testCaseId": "769064dabf2c6a42936c50307d6308b7", "fullName": "tests.test_create_order.TestCreateOrder#test_create_order_not_authorized_user_incorrect_ingredients", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_order"}, {"name": "subSuite", "value": "TestCreateOrder"}, {"name": "host", "value": "DESKTOP-L3DLL49"}, {"name": "thread", "value": "14372-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_order"}]}